//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 03:09:26 PM EDT 
//


package tecintegration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interval">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IntervalReading">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="timePeriod">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interval",
    "intervalReading"
})
@XmlRootElement(name = "IntervalBlock")
public class IntervalBlock {

    @XmlElement(required = true)
    protected IntervalBlock.Interval interval;
    @XmlElement(name = "IntervalReading", required = true)
    protected IntervalBlock.IntervalReading[] intervalReading;

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalBlock.Interval }
     *     
     */
    public IntervalBlock.Interval getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalBlock.Interval }
     *     
     */
    public void setInterval(IntervalBlock.Interval value) {
        this.interval = value;
    }

    /**
     * Gets the value of the intervalReading property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalBlock.IntervalReading }
     *     
     */
    public IntervalReading[] getIntervalReading() {
        return intervalReading;
    }

    /**
     * Sets the value of the intervalReading property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalBlock.IntervalReading }
     *     
     */
    public void setIntervalReading(IntervalReading[] value) {
        this.intervalReading = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "duration",
        "start"
    })
    public static class Interval {

        protected int duration;
        protected int start;

        /**
         * Gets the value of the duration property.
         * 
         */
        public int getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         */
        public void setDuration(int value) {
            this.duration = value;
        }

        /**
         * Gets the value of the start property.
         * 
         */
        public int getStart() {
            return start;
        }

        /**
         * Sets the value of the start property.
         * 
         */
        public void setStart(int value) {
            this.start = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="timePeriod">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cost",
        "timePeriod",
        "value"
    })
    public static class IntervalReading {

        protected int cost;
        @XmlElement(required = true)
        protected IntervalBlock.IntervalReading.TimePeriod timePeriod;
        protected int value;

        /**
         * Gets the value of the cost property.
         * 
         */
        public int getCost() {
            return cost;
        }

        /**
         * Sets the value of the cost property.
         * 
         */
        public void setCost(int value) {
            this.cost = value;
        }

        /**
         * Gets the value of the timePeriod property.
         * 
         * @return
         *     possible object is
         *     {@link IntervalBlock.IntervalReading.TimePeriod }
         *     
         */
        public IntervalBlock.IntervalReading.TimePeriod getTimePeriod() {
            return timePeriod;
        }

        /**
         * Sets the value of the timePeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link IntervalBlock.IntervalReading.TimePeriod }
         *     
         */
        public void setTimePeriod(IntervalBlock.IntervalReading.TimePeriod value) {
            this.timePeriod = value;
        }

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "duration",
            "start"
        })
        public static class TimePeriod {

            protected int duration;
            protected int start;

            /**
             * Gets the value of the duration property.
             * 
             */
            public int getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(int value) {
                this.duration = value;
            }

            /**
             * Gets the value of the start property.
             * 
             */
            public int getStart() {
                return start;
            }

            /**
             * Sets the value of the start property.
             * 
             */
            public void setStart(int value) {
                this.start = value;
            }

        }

    }

}
